manifest {
    name = "MULL"
    author = "Corentin Molitor"
    homePage = "https://github.com/HCL-HUBL/MULL"
    description = "Nextflow to apply the Lipoprotein(a) prediction model"
    mainScript = "MULL.nf"
    version = "0.1.0"
    nextflowVersion = "24+"
}

executor {
    name = 'local'
    cpus = 25
    memory = "100GB"
}

singularity {
        enabled = false
}


params {
    // input / output:
    bams_dir        = ""
    ref             = ""
    outname         = "mull"
    
    // Burgess:
    burgess_vcf     = "${projectDir}/data/burgess_43_snps_sorted.vcf.gz"
    burgess_summary = "${projectDir}/data/burgess_43_snps.summary"

    // KILDA:
    kiv2_kmers  = "${projectDir}/data/kmers_GRCh38_LPA_k31/KIV2_hg38_kmers_6copies_specific.tsv"
    norm_kmers  = "${projectDir}/data/kmers_GRCh38_LPA_k31/LPA_hg38_kmers_1copies_specific.tsv"
    rsids_list  = "${projectDir}/data/lpa_model_rsids.tsv" // this file is optional
    quantiles   = "" //this file is optional

    tools {
        plink = "/opt/progrs/plink"
        gatk = "/opt/progrs/gatk-4.6.2.0/gatk"
        bcftools = "/opt/progrs/bcftools-1.23.1/bcftools"
        samtools = "/opt/progrs/samtools-1.23/samtools"
        bgzip = "bgzip"
        tabix = "tabix"
        jellyfish = "jellyfish"
    }
}
