manifest {
    name = "MULL"
    author = "Corentin Molitor"
    homePage = "https://github.com/HCL-HUBL/MULL"
    description = "Nextflow to apply the Lipoprotein(a) prediction model"
    mainScript = "MULL.nf"
    version = "0.1.0"
    nextflowVersion = "24+"
}

executor {
    name = 'local'
    cpus = 25
    memory = "100GB"
}

singularity {
        enabled = false
}


params {
    bams_dir        = ""
    ref             = ""
    burgess_vcf     = "${projectDir}/data/burgess_43_snps_sorted.vcf.gz"
    burgess_summary = "${projectDir}/data/burgess_43_snps.summary"

    tools {
        plink = "/opt/progrs/plink"
        gatk = ""
        bcftools = ""
        bgzip = ""
        tabix = ""
    }
}
